import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Logo from "./components/atoms/Logo";
import SearchBarWithHamburger from "./components/organisms/SearchBarWithHamburger";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex justify-center`}
      >
        <header className="w-full fixed top-0 flex justify-between bg-[#272727] sm:bg-transparent z-50 text-[#B7B508]">
          <Logo />
          <SearchBarWithHamburger />
        </header>
        <div className="max-w-[1960px] w-full p-[5vw] max-sm:pt-[3rem] ">
          {children}
        </div>
      </body>
    </html>
  );
}
